- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml

- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yml

 
- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connnect to mongodb catalogue
  ansible.builtin.command: mongosh mongodb.eshwar.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output


# - name: print catalogue output
#   ansible.builtin.debug:
#     msg: "{{ catalogue_output }}"

- name: load products into mongodb
  ansible.builtin.shell: mongosh --host mongodb.eshwar.fun </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yml

